### ISSUE TITLE
[BUG] SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x77820f]\n\ngoroutine 436 [running]:\ngo/types.(*Checker).handleBailout(0xc0007fa8c0,

### ISSUE THREAD

**Issue by joe-at-startupmedia** [Templum/govulncheck-action#90]
**Setting a Baseline**
Please start by providing the necessary insights to ensure you can be helped swiftly

Which version of the Action are you using: <>
How does your configuration look like: 

```yaml  
      - name: Go Vulnerability Check
        uses: Templum/govulncheck-action@v1
        with:
          go-version: 1.23.2
```

Logs:

Please share the output of the action, preferably turning the Action into Debug mode. This can be done by specifying an env called `DEBUG` and setting it to `true`.

```
Run Templum/govulncheck-action@v1
Run docker build --build-arg GOLANG_VERSION=1.23.2 --build-arg GH_PAT_TOKEN=$GH_PAT_TOKEN --build-arg GOPRIVATE=$GOPRIVATE --build-arg VULNCHECK_VERSION=v1.0.0 -q -f $GITHUB_ACTION_PATH/Dockerfile -t templum/govulncheck-action:local $GITHUB_ACTION_PATH
  
sha256:cd3800f950226dc2a17f71df466c92a8bf603a6023edaf8693f9a151f5f2a4dd
Run docker run --rm -v $(pwd):/github/workspace --workdir /github/workspace -e GITHUB_TOKEN=*** -e STRICT=false -e PACKAGE=./... -e SKIP_UPLOAD=false -e DEBUG=${DEBUG} -e GITHUB_REPOSITORY=joe-at-startupmedia/version-bump -e GITHUB_REF=refs/heads/master -e GITHUB_SHA=586064c60848a933d036562e68d07189482e438e templum/govulncheck-action:local
5:10AM INF GoEnvironment Details: GOPRIVATE= Go-Arch='amd64' Go-Os='linux' Go-Version='go1.23.2'
5:10AM INF Running govulncheck for package ./... in dir /github/workspace
5:10AM ERR govulncheck exited with none 0 code error="exit status 2" Stderr="panic: runtime error: invalid memory address or nil pointer dereference [recovered]\n\tpanic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x77820f]\n\ngoroutine 436 [running]:\ngo/types.(*Checker).handleBailout(0xc0007fa8c0, 0xc00081dbf0)\n\t/usr/local/go/src/go/types/check.go:404 +0x88\npanic({0x8891c0?, 0xc8e940?})\n\t/usr/local/go/src/runtime/panic.go:785 +0x132\ngo/types.(*StdSizes).Sizeof(0x0, {0x9d2fe0, 0xc95700})\n\t/usr/local/go/src/go/types/sizes.go:229 +0x30f\ngo/types.(*Config).sizeof(...)\n\t/usr/local/go/src/go/types/sizes.go:334\ngo/types.representableConst.func1({0x9d2fe0?, 0xc95700?})\n\t/usr/local/go/src/go/types/const.go:77 +0x86\ngo/types.representableConst({0x9d5d70, 0xc6ce60}, 0xc0007fa8c0, 0xc95700, 0xc00081b658)\n\t/usr/local/go/src/go/types/const.go:93 +0x173\ngo/types.(*Check
5:10AM INF govulncheck information Database=https://vuln.go.dev/ Protocol Version=v1.0.0 Scanner Version=v1.0.0
5:10AM INF Successfully scanned project
5:10AM INF Conversion yielded following stats Call Sites=0 Vulnerabilities=0
5:10AM INF Preparing Report for upload to Github Commit=586064c60848a933d036562e68d07189482e438e Ref=refs/heads/master
5:10AM INF Report was uploaded to GitHub sarif_id=406f82b8-8d0f-11ef-885c-0506fb72b015
5:10AM INF Successfully uploaded Sarif Report to Github, it will be available after processing
```

**Bug Description**
"panic: runtime error: invalid memory address or nil pointer dereference [recovered]\n\tpanic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x77820f]\n\ngoroutine 436 [running]:\ngo/types.(*Checker).handleBailout(0xc0007fa8c0,

**Screenshots**
https://github.com/joe-at-startupmedia/version-bump/actions/runs/11397804013/job/31713843122#step:6:156

**Comment by Templum** [comment]
This error is coming from the govulncheck binary and not from the action. Hence I would kindly ask you to see if you receive the same error when locally running the binary against your code base. 

Alternatively you can also try to update the version of govulncheck, via the action parameter.

**Comment by joe-at-startupmedia** [comment]
Thanks for the quick response.


This adjustment fixes it:
https://github.com/joe-at-startupmedia/version-bump/commit/968efddb023472fd5c00299cf36308c34e73da2f#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R56

Workflow run:
https://github.com/joe-at-startupmedia/version-bump/actions/runs/11411930625/job/31757056950#step:6:1

Without looking into the issue too much, the default version is v1.0.0. When looking at the changelog for v1.0.1 the point of failure in the workflow above was specifically addressed (`types.(*StdSizes).Sizeof`). Maybe consider incrementing the default version by a patch or two?

https://go.googlesource.com/vuln/+/refs/tags/v1.0.1

In either case I will mark this as closed.

**Comment by Templum** [comment]
I will check what you have reported and adjust the version as needed.
